@startuml

actor Donante
actor EntidadBeneficiaria
actor Administrador

(Donar)
(Registrar usuario)
(Registrar necesidades)
(Registrar donación)
(Registrarse)
(Iniciar sesión)
(Gestionar donación)

Donante -- (Donar)
EntidadBeneficiaria -- (Registrar necesidades)
EntidadBeneficiaria -- (Iniciar sesión)
Administrador -- (Registrar usuario)
Administrador -- (Registrar donación)
Administrador -- (Gestionar donación)

(Iniciar sesión) ..> (Registrarse): <include>

@enduml