services:
  postgres-donaciones:
    image: postgres:16
    container_name: donatrack-postgres-donaciones
    environment:
      POSTGRES_DB: donaciones_db
      POSTGRES_USER: donatrack
      POSTGRES_PASSWORD: donatrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_donaciones_data:/var/lib/postgresql/data

  postgres-logistica:
    image: postgres:16
    container_name: donatrack-postgres-logistica
    environment:
      POSTGRES_DB: logistica_db
      POSTGRES_USER: donatrack
      POSTGRES_PASSWORD: donatrack
    ports:
      - "5433:5432"
    volumes:
      - postgres_logistica_data:/var/lib/postgresql/data

volumes:
  postgres_donaciones_data:
  postgres_logistica_data:

